### ISSUE TITLE
keybinding inserting into text

### ISSUE THREAD

**Issue by ggascoigne** [krasa/FrameSwitcher#10]
I changed my keybinding to bring up the list to be ALT-`, when I press this key, it inserts a ` character into wherever the cursor happens to be and then opens up the switch frame window.

 This is on OSX.

**Comment by krasa** [comment]
Imho platform OS/IntelliJ issue, nothing I can do.  Does it happen also for Main menu | VCS | VCS Operations Popup... - if you give it that shortcut?
