### ISSUE TITLE
Does this support switch between tool windows?

### ISSUE THREAD

**Issue by reminia** [krasa/FrameSwitcher#12]
I've tried this plugin. It's very helpful for switching between projects .

But many times I want to switch between tool windows like project window,
terminal window and so on.

**Comment by krasa** [comment]
You can use shortcuts alt+123...  for that

**Comment by reminia** [comment]
yep, with idea default keymap command + number can switch between windows on mac.

I've misunderstood the instruction that 

Plugin for more convenient switching between projects/frames/windows than is alt-tab or Window menu.

Actually, switch between projects only.

**Comment by krasa** [comment]
project=frame=window
window!=tool window
window=project window
:-)
