### ISSUE TITLE
Add switches for opening in same/new window

### ISSUE THREAD

**Issue by axelcostaspena** [krasa/FrameSwitcher#13]
Please can you consider adding next behavior into the frame switcher popup?

ENTER = as is: launch current IDEA project opening action (this depends on user settings: ask, same window, new window...)
Shift-ENTER = open project in current window
Ctrll-ENTER = open project in new window

Kind regards.

**Comment by krasa** [comment]
Sounds good.

**Comment by AlexHaaniWink** [comment]
For if you decide to work on this; Note this JetBrains issue: https://youtrack.jetbrains.com/issue/PY-20579
"Reopen" gives a different dialog than "Open" does.

**Comment by krasa** [comment]
@AlexHaaniWink not sure what to do about that
@axelcostaspena So I implemented it, but in a real life shift-enter sometimes closes a wrong project :X

**Comment by axelcostaspena** [comment]
@krasa sorry for not noticying your comment!! I've just come back since a long time. I have just tested the feature and seems to work like a charm. Really thank you!!!
