### ISSUE TITLE
Key shortcut does not open list when a project is initially opened

### ISSUE THREAD

**Issue by AlexHaaniWink** [krasa/FrameSwitcher#14]
When I start PhpStorm (2017.2) for a project that had no files open, the focus is in the empty editor area.
The shortcut doesn't work then.

When I focus a file in the Project panel, or open a file, or then close it (and have an empty editor area) - in all cases - then the hotkey works just fine.

This is probably something too finicky to bother about. But perhaps you find something.

**Comment by krasa** [comment]
Works fine for me (2017.2.1). 

Try other actions with such dialog - alt+` (Main menu | VCS | VCS Operations Popup...), alt+f1 (Main menu | Navigate | Select In...), and if it is bugged too, then report it to JetBrains.

**Comment by AlexHaaniWink** [comment]
I sure, now it does work just fine. Well, if I can ever reproduce it again I'll open a new issue, with more details. Thanks!
