### ISSUE TITLE
Look in .idea subfolder for icon.png / icon_dark.png

### ISSUE THREAD

**Issue by bazzik** [krasa/FrameSwitcher#28]
- PhpStorm 2020.2.2 on Windows 10
- FrameSwitcher 3.24.4-193 from Oct 08, 2020

From changelog:
>Project icons - can be disabled in settings (looking for: icon.svg, icon.png, src\main\resources\META-INF\pluginIcon.svg, resources\META-INF\pluginIcon.svg, META-INF\pluginIcon.svg)

Can you also re-use icons already used by the IDE? By looking for `.idea/icon.png` (and perhaps `.idea/icon_dark.png` if current GUI Theme is a dark one).

I just do not see much reasons to copy the same icon into the project root if IDE already has one. It could be the last option (after checking other/currently supported locations first).

**Comment by krasa** [comment]
sure, I had no idea that it exists.

**Comment by bazzik** [comment]
Yeah, those are icons that you assign in the IDE for your projects (from Welcome screen mainly). I think it accepts .png files only (not super sure about .svg as IDE lists only .png when trying to select the file with icon).

![image](https://user-images.githubusercontent.com/1482298/95478177-1c96ad00-0981-11eb-8017-af15ddc25bc4.png)

**Comment by krasa** [comment]
thanks! 
you can update

**Comment by bazzik** [comment]
Looks great. Thanks!
