### ISSUE TITLE
Shift/Ctrl modifier key does not seem to work in 2022.3.x

### ISSUE THREAD

**Issue by bazzik** [krasa/FrameSwitcher#39]
Frame Switcher 3.31.0-212

Just installed latest PhpStorm 2022.3.1 on Windows 10 and now the Switch Frame (`Alt+F2`) does not take `Ctrl` and `Shift` into an account (when doing `Shift+Enter` for example). I see the confirmation popup as if no modifier key was pressed.

![image](https://user-images.githubusercontent.com/1482298/210009025-069a6188-165d-465a-94d3-5c3c5ea8c28d.png)

My settings seems to be the same as in previous 2022.2.3 version (at very least in this regard):
![image](https://user-images.githubusercontent.com/1482298/210009100-7c56a4f3-1c13-4eca-bb35-a71fb531b7ca.png)

It was working fine in 2022.2.x.

**Comment by krasa** [comment]
yes :-)
