### ISSUE TITLE
Wrong project names in latest version of IDE

### ISSUE THREAD

**Issue by tomas-langer** [krasa/FrameSwitcher#42]
In the latest early access build, the frame switcher frame shows "Reopen project" instead of the project name for un-opened projects.
It works fine for projects that are open.

Screencast attached

Idea:
```
IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.8102.112, built on January 16, 2024
Licensed to IntelliJ IDEA EAP user: Me
Expiration date: February 15, 2024
Runtime version: 17.0.9+8-b1162.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-14-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8200M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  keymap.windows.as.meta=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  FrameSwitcher (4.2.0-232.7295)
  com.dmarcotte.handlebars (241.8102.112)
  com.intellij.helidon (241.8102.112)
  ru.artyushov (1.4.0)
  hu.hawser.co-author-plugin (2.3)
  com.intellij.kubernetes (241.8102.131)
  Pythonid (241.8102.112)
  org.asciidoctor.intellij.asciidoc (0.41.6)
  com.intellij.nativeDebug (241.8102.112)
  com.intellij.graalvm (241.8102.112)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  com.intellij.jboss.arquillian (241.8102.112)
Kotlin: 241.8102.112-IJ
Current Desktop: ubuntu:GNOME
```
[Screencast from 18.1.2024 16:22:48.webm](https://github.com/krasa/FrameSwitcher/assets/13766491/404d25da-954f-4062-bbd0-6e4b6ac4b77e)

**Comment by muescha** [comment]
I have the same problem :(

PS: as a backup I have assigned a shortcut to: "Recent Projects/Manage Projects ..." `ManageRecentProjects` - but this selector is not as nice as the Frame Switcher
<img width="1023" alt="Bildschirmfoto 2024-01-18 um 18 22 35" src="https://github.com/krasa/FrameSwitcher/assets/184316/29b1355c-e8e8-4b49-a2a3-84d94e17e5fa">

**Comment by muescha** [comment]
thx - I can confirm this is fixed 👍 and work as expected
